data_ingestion:
  fake_news_data_path: "data/Fake.csv"
  real_news_data_path: "data/True.csv"
  raw_data_dir: "artifacts/data_ingestion"
  train_data_path: "artifacts/data_ingestion/train.csv"
  test_data_path: "artifacts/data_ingestion/test.csv"
  val_data_path: "artifacts/data_ingestion/val_data.csv"

split_ratio: 0.2
random_state: 42

data_validation:
  valid_data_path: "artifacts/data_validation/"
  valid_train_data_path: "artifacts/data_validation/train_valid.csv"
  valid_test_data_path: "artifacts/data_validation/test_valid.csv"
  valid_val_data_path: "artifacts/data_validation/val_valid.csv"
  smallest_acceptable_size: 5
  largest_acceptable_size: 10000

word2vec:
  word2vec_model_path: "artifacts/word2vec/word2vec.model"

data_transformation:
  transformed_train_path: "artifacts/data_transformation/transformed_train.csv"
  transformed_test_path: "artifacts/data_transformation/transformed_test.csv"
  transformed_val_path: "artifacts/data_transformation/transformed_val.csv"
  # preprocessor_path: "artifacts/data_transformation/preprocessor.pkl"
  embeded_train_path: "artifacts/data_transformation/embeded_train.kv.npy"
  embeded_y_train_path: "artifacts/data_transformation/embeded_y_train.kv.npy"
  embeded_test_path: "artifacts/data_transformation/embeded_test.kv.npy"
  embeded_y_test_path: "artifacts/data_transformation/embeded_y_test.kv.npy"
  embeded_val_path: "artifacts/data_transformation/embeded_val.kv.npy"
  embeded_y_val_path: "artifacts/data_transformation/embeded_y_val.kv.npy"
  preprocessed_object_path: "artifacts/transformer/preprocessor.pkl"
  max_sequence_length: 300
  embeding_dimension: 300
  padding_type: "post"
  max_vocab_size: 50000
  oov_token: "<OOV>"

model_trainer:
  model_path: "artifacts/model_trainer/model.h5"
  expected_accuracy: 0.8

  output_dim: 300
  input_length: 300
  dropout_rate: 0.6
  optimizer: "adam"
  loss: "binary_crossentropy"
  metrics:
    - "accuracy"
    - "Precision"
    - "Recall"
    - "AUC"
    - "TruePositives"
    - "TrueNegatives"
    - "FalsePositives"
    - "FalseNegatives"

  learning_rate: 0.001
  epochs: 20
  batch_size: 128
  early_stopping_patience: 3
  overfitting_threshold: 0.03
  underfitting_threshold: 0.01
model_evaluation:
  model_evaluation_file_path: "artifacts/model_evaluation/evaluation_report.yaml"
  change_threshold: 0.01
model_pusher:
  export_dir: "artifacts/model_pusher"
  model_file_name: "model.pkl"
  preprocessor_file_name: "preprocessor.pkl"
  raw_data_file_name: "raw_data.csv"
  train_data_file_name: "train.csv"
  test_data_file_name: "test.csv"

ai_agent: news_api_key:"1df3c637e4224650b4fdbb3ae2058467"
